### ISSUE TITLE
Love your work, but have you seen boxcutter/ubuntu?

### ISSUE THREAD

**Issue by dragon788** [tylert/packer-build#10]
I love what you've got going here, the configs are more minimal and tailored to exactly the required boot arguments on newer releases like Xenial (which still seems to suffer from a short kernel args list) but I wonder if it would be more effective to add some of your stuff into boxcutter/ubuntu as well. You seem to have a good handle on the trickier versions like 15.10 and 16.04.

**Comment by tylert** [comment]
I would be happy to add some of my stuff to boxcutter, however, I will likely continue to maintain my own copies here since I'm completely foolish.

If you have suggestions for improvements for the templates here, I am willing to accept pull requests :)

**Comment by tylert** [comment]
It is my intention to eventually automate being able to change the pkgsel, username, password and proxy entries from within the packer template (templating for files outside the main packer template is currently still a missing feature).

Issue #7 has bugged me for a while.  Ideas welcome.

**Comment by dragon788** [comment]
I wouldn't say that's foolish, I'd say that's awesome. I definitely think you are serving a purpose with your templated JSON/YAML conversions, as you mentioned that's something that even Hashicorp hasn't tackled with their weak implementation of no arrays (other than comma separated single line lists) in the user variables.

**Comment by tylert** [comment]
Heh.  At the very least, you can put comments right in the YAML.

So, really, if there are things that you would like to port from here back to boxcutter, that's fine by me;  A quick mention couldn't hurt though :)
