### ISSUE TITLE
Needed to fix "dd" command

### ISSUE THREAD

**Issue by labkey-matthewb** [tylert/packer-build#13]
Running the xenial build failed for me when the "dd" command eventually errors out due to lack of diskspace.  I had to add "|| true" or "||:" to make this work for me.

-        "dd if=/dev/zero of=/ZEROFILL bs=4M",
+        "dd if=/dev/zero of=/ZEROFILL bs=4M ||:",

**Comment by tylert** [comment]
Thanks for reporting the issue.  Pull requests are also very much appreciated.

This issue has now been fixed.
