### ISSUE TITLE
Windows sucks ... as always ... as expected :(

### ISSUE THREAD

**Issue by Tset-Noitamotua** [tylert/packer-build#14]
I was looking for a way to build a minimal Ubuntu desktop and tried this repo. Unfortunately all I get is this:

![image](https://cloud.githubusercontent.com/assets/5635462/26575679/78f00b64-4526-11e7-90e8-792043854bdd.png)

![image](https://cloud.githubusercontent.com/assets/5635462/26575711/9c8e2542-4526-11e7-934a-8c78620fea26.png)

I am running on a Windows 7 64bit machine with recent versions of Packer, Vagrant und VirtualBox. The command above was run in [cmder](http://cmder.net/).

![image](https://cloud.githubusercontent.com/assets/5635462/26575654/64de3c18-4526-11e7-9345-079550346b57.png)

**Comment by Tset-Noitamotua** [comment]
When I try it in a Linux VM (Ubuntu 17.04 Desktop) on same Windows host. I get a "VT-x ... hardware acceleration not available" error althought Microsofts's havdetectiontool says it is (second pic below)

![image](https://cloud.githubusercontent.com/assets/5635462/26578252/5c5d9544-452f-11e7-9852-5b4cb0802a05.png)

![image](https://cloud.githubusercontent.com/assets/5635462/26578319/ab3d5dde-452f-11e7-9593-47934d767bb1.png)

**Comment by Tset-Noitamotua** [comment]
... seems that VirtualBox does still (2017!!!) [not support nested VM with 64 bit Guests](https://www.quora.com/VirtualBox-inside-VirtualBox-Is-that-possible#) :(

**Comment by tylert** [comment]
@Tset-Noitamotua Sorry to hear you had trouble.  Hope things are working now.
