### ISSUE TITLE
ubuntu/xenial/base-uefi.json freezes on GRUB menu

### ISSUE THREAD

**Issue by ardling** [tylert/packer-build#15]
I'm running `./scripts/vbox.sh ubuntu/xenial/base-uefi.json` and it freezes on GRUB menu. 
![vbox_install_error](https://user-images.githubusercontent.com/1092572/27633851-8f4a5f28-5c09-11e7-8042-d203714e6c54.png)

I have tried `./scripts/vbox.sh ubuntu/xenial/base.json`, all works good.

**Comment by ardling** [comment]
working boot_command:
```
"boot_command": [
  "c<wait>",
  "linux /install/vmlinuz ",
  "auto=true ",
  "url=http://{{.HTTPIP}}:{{.HTTPPort}}/{{user `preseed_file`}} ",
  "language={{user `language`}} ",
  "country={{user `country`}} ",
  "locale={{user `locale`}} ",
  "hostname={{user `vm_name`}} ",
  "domain={{user `domain`}} ",
  "interface=auto ",
  "console-setup/ask_detect=false ",
  "keyboard-configuration/layoutcode={{user `keyboard`}} ",
  "vga=788 noprompt quiet --<enter>",
  "initrd /install/initrd.gz<enter>",
  "boot<enter>"
],```

**Comment by tylert** [comment]
@ardling thanks for the report and for testing a working boot command.  Same as the contents of efi_boot_command.txt in the root of the project tree.  I'll try to get your suggested fix applied ASAP.

**Comment by tylert** [comment]
Fixed.  Thanks again.
