### ISSUE TITLE
UEFI Booting on VirtualBox

### ISSUE THREAD

**Issue by ardling** [tylert/packer-build#16]
For Ubuntu systems `FS0:\EFI\debian\grubx64.efi` should be `FS0:\EFI\ubuntu\grubx64.efi`.

**Comment by tylert** [comment]
@ardling Thanks a bunch for testing this--too much to do, not enough time.  I'll try to get these fixes merged ASAFP.

Sorry for the delay, but without an explicit mention for me, I don't tend to see these notices until I remember to log in.

**Comment by tylert** [comment]
Fixed.
