### ISSUE TITLE
gpus?

### ISSUE THREAD

**Issue by Data-drone** [tylert/packer-build#17]
In order to do GPU passthrough I need to run the `virt-install` as:

`sudo virt-install \ 
--name ubuntu-vm \ 
--boot uefi \ 
--machine q35 \
--host-device 4b:00.0 --host-device 4b:00.1 \
...
...`

Does this packer script support this? I am not quite sure where to look to work out what the equivalent `virt-install` bit is

**Comment by tylert** [comment]
@Data-drone sorry, I haven't tried virt-install yet, nor have I done anything with GPUs.  Perhaps you should start by looking at the qemu/kvm documentation to see what they do for that.
