### ISSUE TITLE
vagrant-libvirtd: possible hint

### ISSUE THREAD

**Issue by ardumont** [tylert/packer-build#18]
Hello,

not an issue per say, more like a possible hint in regards to this quote from your README:

> Even though Packer supports QEMU as an officially-supported provider, Vagrant, for some reason, does not. The 3rd-party plugin named "vagrant-libvirt" provides the missing QEMU support for Vagrant. We are unable at this time to verify this fact due to the following errors encountered while trying to run "vagrant up":
> 
> ```
> Error while connecting to libvirt: Error making a connection to libvirt URI qemu:///system?no_verify=1&keyfile=/home/whoa/.ssh/id_rsa:
> Call to virConnectOpen failed: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
> ```

I had this issue this morning. It's because the libvirtd daemon is not running at all.
On debian (testing/buster), i missed the right package installed (`libvirt-daemon-system`).
Upon install, the daemon will be started and this message shall disappear.
 
My 2 cents.

Cheers,

**Comment by tylert** [comment]
@ardumont wow, thanks a lot for your info!  Please note that I would be most happy if you felt you wanted to update the README to mention this improvement.
