### ISSUE TITLE
Post-processor build failure on bionic

### ISSUE THREAD

**Issue by snesbittsea** [tylert/packer-build#20]
Undoubtedly I'm doing stupid, but my attempt to generate a bionic based VirtualBox is failing with the following message:
`==> vbox (vagrant): Creating Vagrant box for 'virtualbox' provider
    vbox (vagrant): Unpacking OVA: build/2018-05-26-18-12-14/base-bionic.ova
    vbox (vagrant): Renaming the OVF to box.ovf...
    vbox (vagrant): Using custom Vagrantfile: source/ubuntu/bionic/base.vagrant
    vbox (vagrant): Compressing: Vagrantfile
==> vbox: Running post-processor: shell-local
==> vbox (shell-local): Post processing with local shell script: /tmp/packer-shell679910228
Build 'vbox' errored: 1 error(s) occurred:

* Post-processor failed: archive/tar: cannot encode header: Format specifies GNU; and GNU cannot encode Uname="snesbitt@fuzzbutt.aussieswithtails.com"`

How is packer-build determining the tar file name? Is there a variable I can set.

Thx,

-steve

**Comment by snesbittsea** [comment]
After further research I'm pretty sure this is an issue with the Packer post-processer for vagrant.

I am logging into my Unix box via a Active Domain Controller and sssd. As a result my uname is a fully qualified domain and I believe this is incompatible with GNUTar header format. Not sure how to fix this yet. I've tried to reconfigure sssd but initial results are good. I'll be opening a bug with Packer.

-steve

**Comment by tylert** [comment]
Please link the Packer issue back to this one when you have it before closing (just in case there is some future rework required).

If you need a workaround in the meantime, there is some information in the README.rst for this project--with a little shell trickery, you can convert an OVA into a box file.

**Comment by snesbittsea** [comment]
[Issue opened in Packer repo](https://github.com/hashicorp/packer/issues/6318) 

Note that I was able to get things to work by adding the setting 
`full_name_format = %1$s`
to the [sshd] section of the /etc/sssd/sssd.conf file followed by a reboot
