### ISSUE TITLE
Crash with Bionic Beaver and Packer 1.2.4

### ISSUE THREAD

**Issue by snesbittsea** [tylert/packer-build#21]
Bionic Beaver VirtualBox image with Packer 1.2.4 crashes. [See: ](https://gist.github.com/snesbittsea/c1fca8c1599f9bddbb2c6a0e9d5a708d#file-gistfile1-txt)
for crash log. Basic issue seems to be with download of iso.

Reverting to Packer 1.2.3 succeeds but generates following message in same area as crash in 1.2.4:
`    vbox: Downloading or copying: http://myserver:8080/ubuntu/ubuntu-18.04-server-amd64.iso
    vbox: Error downloading: Get http://myserver:8080/ubuntu/ubuntu-18.04-server-amd64.iso: dial tcp: lookup myserver on 127.0.0.53:53: server misbehaving
    vbox: Downloading or copying: http://cdimage.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-amd64.iso
 `

**Comment by tylert** [comment]
Interesting.  This very much sounds like a Packer bug.  I shall back the version off to 1.2.3 for these templates in the meantime.

If you happen to raise this bug in the Packer issue tracker, it would be most appreciated if you could please link it back to this ticket before closing this one.

**Comment by tylert** [comment]
Yes, if Packer has crashed, this should very much be reported to them.  Good find.

**Comment by snesbittsea** [comment]
Opened issue: https://github.com/hashicorp/packer/issues/6380

Thx for the help!
