### ISSUE TITLE
Build failed running post-processor: shell-local

### ISSUE THREAD

**Issue by lukas0krupa** [tylert/packer-build#25]
Hi guys,

First of all, very nicely done, you saved me lots of time.

I tried building boxes using QEMU (14.04, 16.04 and 18.04) . I tried to build my own boxes since 4 years ago - quite painfull and builds seems to be working fine without any errors.

However, building VirtualBox box using MacOS somehow failed at the end of the process

```bash
==> vbox: Running post-processor: shell-local
==> vbox (shell-local): Running local shell script: /var/folders/25/4ygjmyhj6ld066wbxqqd2_f80000gp/T/packer-shell007772938
    vbox (shell-local): sed: 1: "build/2018-10-31-10-29- ...": undefined label 'uild/2018-10-31-10-29-24/trusty64S-virtualbox.yaml'
Build 'vbox' errored: 1 error(s) occurred:

* Post-processor failed: Erroneous exit code 1 while executing script: /var/folders/25/4ygjmyhj6ld066wbxqqd2_f80000gp/T/packer-shell007772938

Please see output above for more information.

==> Some builds didn't complete successfully and had errors:
--> vbox: 1 error(s) occurred:

* Post-processor failed: Erroneous exit code 1 while executing script: /var/folders/25/4ygjmyhj6ld066wbxqqd2_f80000gp/T/packer-shell007772938

Please see output above for more information.

==> Builds finished but no artifacts were created.
```
MacOS: 10.14
Packer version: 1.3.2
Virtual box: 5.2.20

Please do let me know if you need more. I haven't tried the box yet, but it seems to be created (I can see .box file in build directory.

**Comment by tylert** [comment]
Sorry for the late reply.  Really busy time.

Unfortunately, I have not seen the error you have reported above.  It really looks like you have modified one of the base templates or else you have something funny going in your `generate_templates` run.

Please have a look at the JSON version of your template and make sure you don't have any errors in the post-processor section that might account for this error.

If your box file works correctly, I would guess that the post-processor with the "sed" line in it is the one that is failing.

**Comment by tylert** [comment]
No reply for over a month.  It would seem like the box file was being created and have been unable to confirm whether there were any local modifications that might have been causing this failure.  Going to close this issue.  Good luck.

**Comment by lukas0krupa** [comment]
Hi, sorry for not responding. Yes, I think I did minor changes - in order
to fit my purpose - but I moved on to something else. Sorry for not letting
you know earlier.

ut 18. 12. 2018 o 2:50 Tyler Tidman <notifications@github.com> napísal(a):
