### ISSUE TITLE
Packer fix error (when running with packer 1.4.2)

### ISSUE THREAD

**Issue by dhbaird** [tylert/packer-build#27]
When I run ./script/generate_templates.sh, `packer fix` (packer 1.4.2) generates this error:

```
Error! Fixed template fails to parse: Failed to cast root level comment value to string

This is usually caused by an error in the input template.
Please fix the error and try again.
```

**Comment by dhbaird** [comment]
The error is caused because the "_ANCHORS" property apparently has to be a string for recent versions of packer to accept it.

**Comment by tylert** [comment]
Yup, I meant to report this issue except reasons.  Thanks for taking the time and super big thanks for the pull-request.
