### ISSUE TITLE
qemuargs build options

### ISSUE THREAD

**Issue by franc01s** [tylert/packer-build#37]
How can I populate
```
      "qemuargs": [
        [
          "-display",
          "none"
        ]]
```
through variables.json as 
```
make BUILD_OPTS='-var-file=variables.json'
```

Any examples will be useful

**Comment by tylert** [comment]
Could you use something like https://github.com/tylert/packer-build/blob/master/source/debian/10_buster/base.yaml#L116-L125 and add a new variable to the `variables:` section?

**Comment by tylert** [comment]
@franc01s you might also try checking the QEMU builder docs at https://www.packer.io/docs/builders/qemu.html#use_default_display.  It might already give you what you need if you simply replace https://github.com/tylert/packer-build/blob/master/source/debian/10_buster/base.yaml#L152 with a new variable.

It this is something that is actively blocking you, it might benefit others as well, and I am willing to accept your pull-requests to try to help improve all these templates.

**Comment by franc01s** [comment]
@tylert thank you a lot to clarified.
I get this working by simply change
```
use_default_display: true
```
in base.yaml

**Comment by tylert** [comment]
Pas de quoi.
