### ISSUE TITLE
Fix ubuntu preseed files to pull in updates while building

### ISSUE THREAD

**Issue by tylert** [tylert/packer-build#7]
The debian templates all pull in the latest updates while building.  Find out why the ubuntu ones fail to do this too.

**Comment by tylert** [comment]
Ubuntu seems to ignore the following:

```
ubiquity ubiquity/download_updates boolean true
ubiquity ubiquity/use_nonfree boolean true
```

**Comment by tylert** [comment]
It would appear that ``d-i pkgsel/upgrade select full-upgrade``` also doesn't work properly either.

**Comment by tylert** [comment]
It may be necessary to remove the junk at the beginning of all the ubuntu preseed files (the junk that was copied from the official ISO).

**Comment by dragon788** [comment]
We trigger updates using a preseed/late_command coupled with an additional script hosted alongside the preseed file (which Packer happily serves but can be tricky to access without knowing the IP of the preseed server from the host instance, I'm not sure if the Packer .HTTPIP var shows up inside the preseed environment).

**Comment by tylert** [comment]
This could probably be done with an inline command.  I'm was just hoping not to have to do that since it's a bit ugly.  The ubiquity/debian installer has such a command--ubiquity just seems to ignore it for some reason.

Might be the same "fix" as proposed for #9--cull the "official" goop at the beginning of the preseed files.

**Comment by dragon788** [comment]
Are you using the desktop ISO or the server one? I thought Ubiquity was
only for the desktop versions of the installers. I typically only use the
d-i commands when building from the server ISO as those consistently work
with only a few exceptions.

**Comment by tylert** [comment]
I never got the desktop ISOs to work correctly (see near bottom of README;  that's why my ubuntu desktop images have been temporarily removed).  It is sufficiently irksome that I even try to use the server ISO when building "real" desktop systems now--it's just a matter of adding a task package and it cuts down on "ISO sprawl" too.

In this case, my use of the term ubiquity here is for "that thing that pretends to be the same as the debian installer (but isn't quite)".  I would like to think that Canonical is not deliberately using a different installer package for their server and desktop ISOs.

**Comment by bdwyertech** [comment]
I typically use this to run a final stage update
```
d-i preseed/late_command string \
  in-target rm -rf /var/lib/apt/lists ; \
  in-target apt-get update ; \
  in-target apt-get -y upgrade ; \
  in-target apt-get -y dist-upgrade ; \
  in-target apt-get -y autoremove ; \
  in-target apt-get autoclean ; \
  in-target apt-get clean
```

**Comment by tylert** [comment]
Pretty sure that http://cdimage.ubuntu.com/netboot/ is going to be a slightly better and less hackish way of making sure all updates are yanked in at build time.

This might also get around some of the stupidity of ubiquity as well and allow better automation for building desktop images too.
