### ISSUE TITLE
Xenial builds:  get past the postfix config prompt

### ISSUE THREAD

**Issue by tylert** [tylert/packer-build#9]
At the moment, the latest xenial builds prompt for postfix configuration during the install.  Need to get past this step.

**Comment by tylert** [comment]
Find out if this still happens with "this week's" ubuntu installer image.

**Comment by dragon788** [comment]
Postfix didn't appear to prevent the install from finishing when I built using your boot stanza earlier this week and the boxcutter update scripts.

**Comment by tylert** [comment]
![screenshot from 2016-03-03 17 22 19](https://cloud.githubusercontent.com/assets/152904/13511690/33f00eb4-e164-11e5-9073-f7fec36a5ab6.png)

**Comment by tylert** [comment]
I suspect it's related to the fact that the preseed file is a hybrid of the official canonical junk + stuff I added.  The fix is probably to simply remove the canonical stuff--making the ubuntu preseed files look more like the debian ones.

**Comment by dragon788** [comment]
Ah yeah, if you selected a default recipe that includes smtp or some other
software that requires postfix to email (as root) that wasn't previously
installed. I'll see if I can find our debconf answers file to see how we
answered this on our systems when mysql or something required postfix to be
configured.

**Comment by tylert** [comment]
Yup.  Probably not worth bothering with the hack unless you feel very strongly that having preseed files that look *kinda* like ubuntu is important (I always disliked having undocumented junk in the preseed files).  I am fairly certain the fix can be not too ugly but still work.

When I next have some time, I plan to remove the top parts of these ubuntu preseed files and confirm they can be tricked into working correctly.  That is, unless you wish to give it a go first.

(Geez, I really should bodge together a proper build server for these someday.  Hosting pre-built images is also one of my longer-term goals for these.)

**Comment by tylert** [comment]
Fixed in master.
